### ISSUE TITLE
Move transformation methods off of Reactable

### ISSUE THREAD

**Issue by danschultz** [danschultz/frappe#29]
When Reactable has transformation methods, like `map`, `zip`, etc, it's unclear what type of Reactable the transformation returns. Moving these methods to Property and EventStream makes it clearer that a transformation of a Property will return another Property.

I think it makes sense to keep the *listener* methods on Reactable. This includes properties like `first` and `last`, and maybe also methods like `toList()` etc.

**Comment by Andersmholmgren** [comment]
One thing to keep in mind is what is the difference between a property and an event stream. 
In my mind it is just that properties have a notion of holding on to their current value. Ie that it is a special type of event stream. Does it make sense for property to extend eventstream?

**Comment by Andersmholmgren** [comment]
I definitely agree with your last point that transforming a property should produce another property. Ie if the input stream replays the last value then the transformed one should. This is the most intuitive and useful approach. 

I noticed that stream.ext also hasn't hat concept and leaves it all as Stream.  

I'm with you in that I prefer a separate class that identifies something as "a stream that replays its current value" and I like the name Property for that even though a separate type isn't strictly needed I guess. 

However if you step out a level from how the event streams and properties originate and look at how they differ semantically then is there any more difference than just that properties remember their last value?

Aren't they identical in behavior other than in relation to the current value?

**Comment by danschultz** [comment]
I need to think about this a bit more and also want to take a look at some implementations in languages like Scala and Haskell. I'll draft up a spec and throw it up on the wiki in a week or two.

**Comment by danschultz** [comment]
Pushed some work to the v0.4 branch which includes some changes to the class hierarchy:

* `Reactable` now extends from `Stream`.
* `Reactable` now contains all transformation and combinator methods.
