### ISSUE TITLE
EventStream.debounce - code or documentation error?

### ISSUE THREAD

**Issue by radicaled** [danschultz/frappe#30]
This is the documentation for `EventStream.debounce`:

```
Returns a new stream that upon forwarding an event from this stream, will ignore any subsequent events until duration, after which the last event will be forwarded.
```

In practice, what `EventStream.debounce` seems to do is wait for `duration` to pass without any new events having come in, and _then_ forwards the last received event. This means that a time span longer than the specified `duration` can pass without an event being forwarded -- eg if a user is typing into a text field rapidly no 'content-modified' events get fired until they stop for at least `duration`.

Using 0.3.2.

**Comment by danschultz** [comment]
This is a documentation error in 0.3.2. It's been corrected in 0.4. The default behavior for debounce is similar to that in RxJS and Bacon. I think what your looking for is an `immediate` option that you can pass to debounce, or a separate method, like `debounceImmediate`.

**Comment by radicaled** [comment]
I think I'm looking for functionality similar to `throttle` (forgive me if I've gotten my terminology screwed up):

Once an event is received, wait for `duration` and then forward the last event received, even if events are still flowing into the stream.

So if a user were typing into a text box, you'd fire a change event every `duration`, and only the last one that came in before the duration.

**Comment by danschultz** [comment]
Makes sense, I created ticket #34 to track the implementation. Let me know if the description doesn't cover your use case.

**Comment by radicaled** [comment]
That is actually what I'm looking for. I'll watch that issue -- thanks. :)

The documentation still seems to be incorrect for debounce, though: https://github.com/danschultz/frappe/blob/5f328c3c14a7fee31d93d6c3d8752c2bf060717a/lib/src/reactable.dart#L153

```
  /// Ignores events for a given duration, then delivers the last event in
  /// the stream after the duration has passed. Errors occurring on the
  /// source stream will not be ignored. If the source stream is a broadcast
  /// stream, then the transformed stream will also be a broadcast stream.
```

Behaviorally, it's "... after the duration has passed without receiving an event."

bacon.js seems to describe that as the "quiet period," so I guess it has no technical term I can refer to it as:

```
observable.debounce(delay) throttles stream/property by given amount of milliseconds, but so that event is only emitted after the given "quiet period".
```
