### ISSUE TITLE
Cheap way to get current value of Property?

### ISSUE THREAD

**Issue by jonaskello** [danschultz/frappe#46]
Probably not the FRP way of doing things, but I would like to just get the value of Property._currentValue. I could do this:

var currentValue = await property.first;

But I think that would be expensive as it involves creating streams and futures and it would not return if there are no current value. Another solution would be to listen to the value and cache it:
```dart
class Foo {
  var _currentValue;
  Foo(provider) =>  provider.property.listen((v) => _currentValue = v);
  Bar() {  ... do something with _currentValue }
}
```
So I guess what I am proposing is that the _currentValue and _hasCurrentValue is exposed as:
```dart
if(property.hasCurrentValue) {
   var currentValue = property.currentValue;
   ...
}
```

Again, I understand that this probably is not the FRP way of doing things, just would be practical in some cases where I need the current value. Or maybe I am overlooking some other way of doing it?

**Comment by danschultz** [comment]
I'm pretty hesitant to add a public `currentValue` field to Frappe. If this is important for you, I'd recommend maybe creating a Signal wrapper for this functionality.

**Comment by Andersmholmgren** [comment]
I struggled with this too but also convinced myself it was not the FRP way.
It happens mostly when mixing an imperative style with FRP.
