### ISSUE TITLE
frappe and ddc?

### ISSUE THREAD

**Issue by devoncarew** [danschultz/frappe#47]
Have you tried compiling an app that uses frappe with the ddc compiler (`dev_compiler`)? We're seeing analysis issues reported from ddc - I don't know if it's the ddc being aggressive in its reporting or type issues with frappe.

https://github.com/dart-atom/dartlang/issues/129

**Comment by danschultz** [comment]
I haven't yet. These issues are probably being triggered because `EventStream` and `Property` are changing the return types that `Reactable` is defining to be either an `EventStream` or `Property`. I haven't seen any warnings from the analyzer about doing this, so I figured this approach was kosher.

**Comment by devoncarew** [comment]
@radicaled took a stab at addressing the warnings here: https://github.com/danschultz/frappe/compare/master...radicaled:fix_type_problems. I think it boiled down to adding a bit more generic type info in a few places.

The ddc is a bit more strict than the analyzer. I don't think these are issues per se, but hints for places where adding more type info would let the ddc generate better code.

**Comment by danschultz** [comment]
@radicaled those changes seems simple enough. If you submit a PR I can merge it.

**Comment by radicaled** [comment]
There's also this: https://github.com/danschultz/stream_transformers/compare/master...radicaled:fix_type_problems

**Comment by danschultz** [comment]
Version 0.4.0+5 is up on pub.

@radicaled send over a PR for stream_transformers and I'll look it over.
