### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by brianegan** [danschultz/frappe#52]
Hey, thanks for making such a cool project! I really like a lot of things about this codebase and stream_transformers, and was thinking about submitting some PRs to update this library a bit, but seems this project hasn't seen much activity lately. Is this project / stream transformers still active and accepting PRs?

**Comment by pratikpparikh** [comment]
Similar to @brianegan  i think both of the projects can help many do reactive programming on client side and server side.  @danschultz do you have any interest in continuing this work?

**Comment by brianegan** [comment]
@pratikpparikh As a heads up, I found RxDart and started helping out over there. Covers much of, if not more functionality at this point and is Strong mode compliant!
